[ui]
default-command = "log"
movement.edit = true
merge-editor = "nvim"

[ui.diff]
format = "git"
tool = ["difft", "--color=always", "$left", "$right"]

[merge-tools.nvim]
program = "nvim"
merge-args = ["-f", "-d", "$output", "-M",
    "$left", "$base", "$right",
    "-c", "wincmd J", "-c", "set modifiable",
    "-c", "set write"]
merge-tool-edits-conflict-markers = true


[template-aliases]
# Username part of the email address
'format_short_signature(signature)' = 'signature.email().local()'

[revset-aliases]
'thisofftrunk()' = 'trunk()..@ | (..trunk() ~ ..@) | latest(..trunk() & ..@)'

# found at https://ofcr.se/jujutsu-merge-workflow
#   usage: jj rebase -s 'all:roots(allofftrunk())' -d main
#   will rebase all
'allofftrunk()' = 'trunk()..@'


# found at https://reasonablypolymorphic.com/blog/jj-strategy/index.html
'accordion()' = '@ | bases | branches | curbranch::@ | @::nextbranch | downstream(@, branchesandheads)'
'bases' = 'trunk()'
'downstream(x,y)' = '(x::y) & y'
'branches' = 'downstream(trunk(), branches()) & mine()'
'branchesandheads' = 'branches | (heads(trunk()::) & mine())'
'curbranch' = 'latest(branches::@- & branches)'
'nextbranch' = 'roots(@:: & branchesandheads)'

[aliases]
l = ["log", "-r", 'thisofftrunk()']
lh = ["log", "-r", "@-"]
r = ["log", "-r", "::@", "--limit", "10"]
lf = ["log", "-T" , "builtin_log_compact_full_description"]

[git]
private-commits = "description(glob:'private:*') | description(glob:'local:*') | description(glob:'stash:*') | description(glob:'wip:*')"

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  surround(
    "\nJJ: ╭───────────────────────────────────────────────────────────────────────────────\n",
    "JJ: ╰───────────────────────────────────────────────────────────────────────────────\n",
    indent("JJ: │ ", diff.git()),
  )
)
'''
