- clean:
    ~/:
    ~/.config:
      recursive: true

- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.config/atuin: atuin
    ~/.config/git: git/config
    ~/.config/macrowhisper: macrowhisper
    ~/.config/kitty/:
      path: kitty/*
      glob: true
    ~/.config/lazygit/config.yml: lazygit/config.yml
    ~/.config/nnn/plugins/nuke: nnn/plugins/nuke
    ~/.config/nvim: nvim
    ~/.config/starship.toml: starship/starship.toml
    ~/.config/task: taskwarrior
    ~/.config/ghostty: ghostty
    ~/.config/weechat: weechat
    ~/.config/zellij/config.kdl: zellij/config.kdl
    ~/.config/zellij/layouts/:
      path: zellij/layouts/*
      glob: true
    ~/.gitconfig: git/_gitconfig
    ~/.zshenv: zsh/HOME_zshenv
    ~/.vscodevimrc: vscode/HOME_vscodevimrc
    ~/.config/jj/config.toml: jj/jjconfig.toml
    ~/.config/jj/conf.d/:
      path: jj/conf.d/*
      glob: true
    ~/.ctags: ctags/HOME_ctags
    ~/.vsnip: nvim/vsnip
    ~/.lesskey: less/DOT_lesskey

- brewfile:
    file: homebrew/Brewfile
    stdout: true
    stderr: true

- shell:
    - ["nvim --headless +BfcPostInstall +qall", "Installing and Updating vim plugins"]
