- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.config/kitty/:
      path: kitty/*
      glob: true
    ~/.config/lazygit/config.yml: lazygit/config.yml
    ~/.config/nvim: nvim
    ~/.zshenv: zsh/HOME_zshenv

- brewfile:
    file: homebrew/Brewfile
    stdout: true
    stderr: true

- asdf:
    - plugin: elixir
      global: 1.13.0-otp-24
      versions:
        - 1.13.0-otp-24

    - plugin: erlang
      global: 24.1.2
      versions:
        - 24.1.2

    - plugin: nodejs
      global: 16.4.2
      versions:
        - 16.4.2
        - 14.17.0

    - plugin: ruby
      global: 2.7.3
      versions:
        - 2.7.3

- shell:
    - ["nvim --headless +BfcPostInstall +qall", "Installing and Updating vim plugins"]
