- clean:
    ~/:
    ~/.config:
      recursive: true

- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.config/git: git/config
    ~/.config/kitty/:
      path: kitty/*
      glob: true
    ~/.config/lazygit/config.yml: lazygit/config.yml
    ~/.config/nnn/plugins/nuke: nnn/plugins/nuke
    ~/.config/nvim: nvim
    ~/.config/starship.toml: starship/starship.toml
    ~/.gitconfig: git/_gitconfig
    ~/.zshenv: zsh/HOME_zshenv
    ~/.vscodevimrc: vscode/HOME_vscodevimrc

- brewfile:
    file: homebrew/Brewfile
    stdout: true
    stderr: true

- asdf:
    - plugin: elixir
      global: 1.14.4-otp-25
      versions:
        - 1.14.4-otp-25

    - plugin: erlang
      global: 25.3.2
      versions:
        - 25.3.2

    - plugin: nodejs
      global: 19.8.1
      versions:
        - 19.8.1

- shell:
    - ["nvim --headless +BfcPostInstall +qall", "Installing and Updating vim plugins"]
