- clean:
    ~/:
    ~/.config:
      recursive: true

- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.config/git: git/config
    ~/.config/kitty/:
      path: kitty/*
      glob: true
    ~/.config/lazygit/config.yml: lazygit/config.yml
    ~/.config/nnn/plugins/nuke: nnn/plugins/nuke
    ~/.config/nvim: nvim
    ~/.config/starship.toml: starship/starship.toml
    ~/.gitconfig: git/_gitconfig
    ~/.zshenv: zsh/HOME_zshenv

- brewfile:
    file: homebrew/Brewfile
    stdout: true
    stderr: true

- asdf:
    - plugin: elixir
      global: 1.13.0-otp-24
      versions:
        - 1.13.0-otp-24

    - plugin: erlang
      global: 24.1.2
      versions:
        - 24.1.2

    - plugin: haskell
      global: 8.10.7
      versions:
        - 9.2.1
        - 8.10.7

    - plugin: nodejs
      global: 16.4.2
      versions:
        - 16.4.2
        - 14.17.0

    - plugin: ruby
      global: 2.7.3
      versions:
        - 2.7.3

- shell:
    - ["nvim --headless +BfcPostInstall +qall", "Installing and Updating vim plugins"]
