- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.config/kitty/:
      path: kitty/*
      glob: true
    ~/.config/nvim: nvim
    ~/.config/lazygit/config.yml: lazygit/config.yml

- brewfile:
    file: homebrew/Brewfile
    stdout: true
    stderr: true
