- clean:
    ~/:
    ~/.config:
      recursive: true

- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.config/atuin: atuin
    ~/.config/git: git/config
    ~/.config/kitty/:
      path: kitty/*
      glob: true
    ~/.config/lazygit/config.yml: lazygit/config.yml
    ~/.config/nnn/plugins/nuke: nnn/plugins/nuke
    ~/.config/nvim: nvim
    ~/.config/nix: nix
    ~/.config/starship.toml: starship/starship.toml
    ~/.gitconfig: git/_gitconfig
    ~/.zshenv: zsh/HOME_zshenv
    ~/.vscodevimrc: vscode/HOME_vscodevimrc

- brewfile:
    file: homebrew/Brewfile
    stdout: true
    stderr: true

- shell:
    - ["nvim --headless +BfcPostInstall +qall", "Installing and Updating vim plugins"]
    - ["sudo candy setup", "Setting up candy"]
    - ["brew services start candy", "Starting candy service"]
