brew "asdf"
brew "coreutils"
brew "bat"
brew "fd"
brew "git-branchless"
brew "glow"
brew "gnupg"
brew "gron"
brew "jq"
brew "neovim"
brew "nnn"
brew "ripgrep"
brew "w3m"
brew "zsh"

# Tapped formulas
tap "jesseduffield/lazygit"
brew "jesseduffield/lazygit/lazygit"

# Cask formulas
cask "kitty"
cask "vimr"

# vim:ft=ruby
