brew "asdf"
brew "coreutils"
brew "bat"
brew "broot"
brew "fd"
brew "git-branchless"
brew "glow"
brew "gnupg"
brew "gron"
brew "jo"
brew "jq"
brew "mitmproxy"
brew "neovim"
brew "nnn"
brew "ripgrep"
brew "starship"
brew "w3m"
brew "xh"
brew "zsh"

# Tapped formulas
tap "jesseduffield/lazygit"
brew "jesseduffield/lazygit/lazygit"

brew "hashicorp/tap/terraform-ls"

# Cask formulas
cask "kitty"
cask "neovide"

# vim:ft=ruby
