if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

fpath+=( \
  /opt/homebrew/share/zsh/site-functions \
)

export path=('/opt/homebrew/bin' '/opt/homebrew/sbin' $path)
